# edit this file to adjust testing parameters
# sourced by bench.sh and show-results.sh

# user editable parameters
N=8192			# number of requests per run
LOW_C=1			# lowest test concurrency
MID_C=8			# middle test concurrency
HIGH_C=64		# highest test concurrency
RUNS_PER_TEST=5 	# number of times to repeat each specific test variation

# the following parameters should not be modified
OS=`uname -s`		# needed for OS specific options
rundir="`pwd`/runners"	# directory containing run scripts
TMP_DIR="`pwd`/tmp"	# directory containing test outputs
PORT=8080		# http binds to this port

