#!/bin/sh

if [ $# -gt 0 ]; then
  port=$1
else
  echo "no port provided, defaulting to 8080"
  port=8080
fi

OS=`uname -s`

if [ $OS = 'Linux' ]; then 
  ss -tunlp | grep "\:${port}"
elif [ $OS = 'FreeBSD' ]; then 
  sockstat -46l -P tcp -p ${port}
elif [ $OS = 'OpenBSD' ]; then
  fstat | grep internet|grep "\:${port}"
elif [ "$OS" = 'Darwin' ]; then
  lsof -i :${port} -sTCP:LISTEN
fi

